Master to develop
sora-xor/sora2-network pull request #670
Opened 2023-08-15 23:39 UTC by vovac12

2023-08-16 14:02 UTC, wer1st requested changes

2023-08-16 14:02 UTC, wer1st commented on common/src/primitives.rs
> +    #[cfg(feature = "wip")] // order-book
We should not change it in the `develop` branch

2023-08-16 19:59 UTC, N1ghtStorm approved these changes

2023-08-17 07:14 UTC, wer1st approved these changes

2023-08-17 07:15 UTC, wer1st commented
This PR reopens #499

2023-08-18 10:07 UTC, Alexey-N-Chernyshov approved these changes

2023-08-28 08:23 UTC, merged