OrderBook: market maket network fee
sora-xor/sora2-network pull request #762
Opened 2023-10-04 10:35 UTC by wer1st

Introduce the custom reduced network fee for maket makers.
`place_limit_order` the following network fees:
- reduced fee if the limit order successfully placed
- regular fee if some error occurs
- regular fee if the limit order was converted into a market order

2023-10-04 14:50 UTC, wer1st commented on runtime/src/xor_fee_impls.rs
> +            RuntimeCall::OrderBook(order_book::Call::place_limit_order { .. }) => true,
Yes, just forgot to delete

2023-10-04 15:12 UTC, bragov4ik requested changes
Not sure about computation error part
LGTM other than this

2023-10-04 15:36 UTC, wer1st commented on pallets/order-book/src/fee_calculator.rs
> +        (const_part + dynamic_part).try_into_balance().ok()
It is better to return `None`

2023-10-04 15:36 UTC, bragov4ik approved these changes

2023-10-04 15:37 UTC, wer1st commented on pallets/order-book/src/fee_calculator.rs
> +    pub fn place_limit_order_fee(
It is better to have a type (struct) instead of standalone fn

2023-10-05 07:02 UTC, bragov4ik approved these changes

2023-10-05 11:36 UTC, vovac12 approved these changes

2023-10-05 14:21 UTC, merged