ci: gh code analysis
sora-xor/sora2-network pull request #797
Opened 2023-10-23 17:26 UTC by Alexey-N-Chernyshov

2023-10-24 17:39 UTC, wer1st commented
We cannot remove all `#![allow(clippy::all)]` because of Jenkins

2023-10-25 06:36 UTC, Alexey-N-Chernyshov commented
`We cannot remove all #![allow(clippy::all)] because of Jenkins`
Yes, I'll return them. I demonstrated that Jenkins the GH action is failing now.

2023-10-25 12:10 UTC, wer1st approved these changes

2023-10-26 05:47 UTC, wpi86 requested changes

2023-10-26 05:47 UTC, wpi86 commented on .github/workflows/static_analysis.yml
> +      - uses: actions/checkout@v4
pin version on all actions

2023-10-27 05:59 UTC, wpi86 approved these changes

2023-10-30 05:54 UTC, wpi86 approved these changes

2023-10-31 05:44 UTC, wpi86 approved these changes

2023-11-07 09:53 UTC, merged