Apollo Platform
sora-xor/sora2-network pull request #946
Opened 2024-03-22 09:23 UTC by DanijelCBS

The Apollo Protocol is the first lending and borrowing platform on the SORA network and a part of the Ceres ecosystem. Apollo enables its users to deposit and borrow assets on the SORA network. Depositors can provide liquidity and secure passive income through interest, while borrowers can leverage their assets without selling them and pay interest for this service.

2024-03-27 11:52 UTC, Alexey-N-Chernyshov reviewed
Please, add minimal amount on lending and borrowing amounts, so attacker will not create empty entities.

2024-03-27 11:52 UTC, Alexey-N-Chernyshov commented on pallets/apollo-platform/src/lib.rs
> +        ) -> DispatchResultWithPostInfo {
Please, check that `borrowing_amount` is more than some minimal amount to prevent attack with blowing of `UserBorrowingInfo`.

2024-03-27 11:52 UTC, Alexey-N-Chernyshov commented on pallets/apollo-platform/src/lib.rs
> +            ensure!(lending_amount > 0, Error::<T>::InvalidLendingAmount);
Please, check that `lending_amount` is more than some minimal amount to prevent attack with blowing of `UserLendingInfo`.

2024-03-29 06:00 UTC, Alexey-N-Chernyshov approved these changes

2024-03-29 13:13 UTC, Alexey-N-Chernyshov approved these changes

2024-04-02 15:50 UTC, vovac12 approved these changes

2024-04-02 16:04 UTC, vovac12 requested changes

2024-04-02 16:04 UTC, vovac12 commented on pallets/apollo-platform/src/lib.rs
> +            let user_infos = UserBorrowingInfo::<T>::get(asset_id, user.clone()).unwrap();
Remove `unwrap()` here and below

2024-04-04 10:45 UTC, merged