[DOPS-3156]: automatize runtime upgrades
sora-xor/sora2-network pull request #999
Opened 2024-04-22 14:08 UTC by f33r0

# Task

[DOPS-3156]: automatize runtime upgrades

## Changes

1. Modified script Dockerfile

[DOPS-3156]: https://soramitsu.atlassian.net/browse/DOPS-3156

2024-04-22 16:00 UTC, Alexey-N-Chernyshov reviewed
Do we need `framenode_runtime.compact.compressed.wasm` binary file in repo? May be add it to `gitignore`?

2024-04-22 16:00 UTC, Alexey-N-Chernyshov commented on misc/runtime_upgrade/Dockerfile
> +CMD ["python", "main.py"]
```suggestion
CMD ["python", "main.py"]

```

2024-04-22 16:00 UTC, Alexey-N-Chernyshov commented on runtime/src/migrations.rs
> +#[cfg(feature = "ready-to-test")] // kensetsu
#998 missing, please merge `master` when the PR is merged.

2024-04-24 05:43 UTC, safinsaf commented on Jenkinsfile
> +@Library('jenkins-library@feature/dops-3156/runtime_upgrade') _
Pls do not forget to remove before merge

2024-04-24 05:43 UTC, safinsaf approved these changes

2024-04-24 06:39 UTC, wpi86 requested changes

2024-04-24 06:39 UTC, wpi86 commented on misc/runtime_upgrade/Dockerfile
> +COPY ./misc/runtime_upgrade/main.py \
It's more secure if we have immutable scripts.

2024-04-28 00:09 UTC, C4tWithShell approved these changes

2024-05-06 13:43 UTC, Cre-eD approved these changes

2024-05-07 05:26 UTC, wpi86 requested changes
fix script permissions

2024-05-07 06:02 UTC, RamilMus approved these changes

2024-05-07 06:39 UTC, wpi86 approved these changes

2024-05-07 09:10 UTC, Alexey-N-Chernyshov approved these changes

2024-05-13 05:42 UTC, merged